blog/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  resources :blogposts do
    resources :comments
  end

      root 'welcome#index' 
   

   match "/users/sign_out", via: [:get, :delete], to: "devise/sessions#destroy"

  get '/blogposts/index.html.erb', to: 'blogposts#index'
  get '/profiles/team.html.erb', to: 'profiles#team'
  get '/profiles/Haya.html', to: 'profiles#Haya'
  get '/profiles/Amr.html', to: 'profiles#Amr'
  get '/profiles/Sandra.html', to: 'profiles#Sandra'
  get '/profiles/Marina.html', to: 'profiles#Marina'
  get '/profiles/Sara.html', to: 'profiles#Sara'
  get '/profiles/Seif.html', to: 'profiles#Seif'
  get '/profiles/Omar.html', to: 'profiles#Omar'
  get '/profiles/Christianne.html', to: 'profiles#Christianne'
  get '/customs/Contact Us.html', to: 'customs#Contact Us'
  get '/profiles/customs/Contact Us.html', to: 'customs#Contact Us'
  get '/blogposts/customs/Contact Us.html', to: 'customs#Contact Us'
  get '/Home.html', to: 'customs#Home'
  get '/profiles/customs/Home.html', to: 'customs#Home'
  get '/blogposts/customs/Home.html', to: 'customs#Home'

 

end

blog/app/models/blogpost.rb
class Blogpost < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	validates :title, presence: true,
                    length: { minimum: 5 }
end

blog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :blogpost
end

blog/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  	before_action :user_signed_in?
	before_action :current_user
	before_action :user_session


end

blog/app/controllers/blogposts_controller.rb
class BlogpostsController < ApplicationController
 def index
    @blogposts = Blogpost.all
  end
def show
	@blogpost = Blogpost.find(params[:id])
end
def new
	@blogpost = Blogpost.new
end

def edit
	@blogpost = Blogpost.find(params[:id])
end

def create
	@blogpost = Blogpost.new(blogpost_params)
	
	if @blogpost.save
		redirect_to @blogpost
	else
		render 'new'
	end
end

def update
	@blogpost = Blogpost.find(params[:id])
	if @blogpost.update(blogpost_params)
		redirect_to @blogpost
	else render 'edit'
	end
end
def destroy
  @blogpost = Blogpost.find(params[:id])
  @blogpost.destroy
 
  redirect_to blogposts_path
end

private
def blogpost_params
	params.require(:blogpost).permit(:title, :text)
end

end

blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
def create
    @blogpost = Blogpost.find(params[:blogpost_id])
    @comment = @blogpost.comments.create(comment_params)
    redirect_to blogpost_path(@blogpost)
  end
  def destroy
    @blogpost = Blogpost.find(params[:blogpost_id])
    @comment = @blogpost.comments.find(params[:id])
    @comment.destroy
    redirect_to blogpost_path(@blogpost)
  end
 
 
  private
    def comment_params
      params.require(:comment).permit(:user, :body)
    end
end

blog/app/controllers/customs_controller.rb
class CustomsController < ApplicationController
  def custom
  end
end

blog/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def team
  end
end

blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/blogposts_helper.rb
module BlogpostsHelper
end

blog/app/helpers/comments_helper.rb
module CommentsHelper
end

blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

blog/app/views/blogposts/_form.html.erb
<style>

h1 {
  text-align: left;
}
textarea {

  width: 500pt;
  height: 150pt;

}
p {
  text-align: left;
}
</style>
<%= form_for @blogpost do |f| %>
 
  <% if @blogpost.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@blogpost.errors.count, "error") %> prohibited
        this blogpost from being saved:
      </h2>
      <ul>
        <% @blogpost.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

blog/app/views/blogposts/edit.html.erb
<h1>Edit blogpost</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', blogposts_path %>

blog/app/views/blogposts/index.html.erb
<!DOCTYPE html>
  <style>
    
    body{
      background-color: rgb(225,225,225);
      }

      h1 {
        font-family: playfair display;
        font-size: 17pt;
        font-weight: bold;
        color: #E30613;
        text-align: center;
    }

    th {
        color: black;
      text-align: center;
      font-family: alegreya;
      font-weight: none;
      text-decoration: none;
      width: 90pt;
      font-size: 13.5pt;

    }

    a {
      color: black;
      text-align: center;
      font-family: alegreya;
      font-weight: none;
      text-decoration: none;
      display: block;
      width: 90pt;
      font-size: 13.5pt;
    }

    a:hover {
        color: #E30613;
        background-color: none;
      }

  </style>

<body>

  <h1>Our Blogposts</h1> <br></br>
  <%if current_user.try(:admin?)%>
  <a><%= link_to '~ New Post', new_blogpost_path %></a><br></br>
  
  <%end%>

</body>


<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @blogposts.each do |blogpost| %>
    <tr>
      <td><%= blogpost.title %></td> 
      <td><%= blogpost.text %></td>
      <td><%= link_to 'Show', blogpost_path(blogpost) %></td>
      <%if current_user.try(:admin?)%>
      <td><%= link_to 'Edit', edit_blogpost_path(blogpost) %></td>
      <td><%= link_to 'Destroy', blogpost_path(blogpost),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
              <%end%>
    </tr>
  <% end %>
</table>

blog/app/views/blogposts/new.html.erb
<style>
	
	h1 {
		font-family: playfair display;
		font-size: 16pt;
		color: #E30613;
		}


</style>

<h1>New blogpost</h1>
<%= render 'form' %>

blog/app/views/blogposts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @blogpost.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @blogpost.text %>
</p>
<h2>Comments</h2>
<%= render @blogpost.comments %>
 

<style>

a {
text-align: center;
}




</style>




<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>


<div class="fb-share-button" data-href="https://developers.facebook.com/docs/plugins/" data-layout="button_count"></div>


<a class="twitter-share-button"
  href="https://twitter.com/share">Tweet</a>
<script>window.twttr=(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],t=window.twttr||{};
if(d.getElementById(id))return;js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);t._e=[];t.ready=function(f){t._e.push(f);};return t;}
(document,"script","twitter-wjs"));
</script><script src="https://apis.google.com/js/platform.js" async defer></script>
<g:plus action="share"></g:plus>

blog/app/views/comments/_comment.html.erb
<p>
  <strong>User:</strong>
  <%= comment.user %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
<p>
  <%if current_user.try(:admin?)%>
  <a><%= link_to 'Destroy Comment', [comment.blogpost, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %></a>
  <%end%>
</p>

blog/app/views/comments/_form.html.erb
<style>
  
h2 {
  text-align: center;
}





</style>



<%= form_for([@blogpost, @blogpost.comments.build]) do |f| %>
  <p>
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
  <p><%if current_user.try(:admin?)%>
<%= link_to 'Edit', edit_blogpost_path(@blogpost) %>
<%end%>
</p>
<% end %>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<style type="text/css">
	h1{ color:#F00;
		font-size: 32pt;
		font-family: Times;
		text-align: center;
	}
	/*h2{text-align: left; } */
	/*h3{text-align: right;}*/
	body{
		text-align: center,justify;
		background: rgba(255,255,255,1);
		color:blue;
		font-family: helvetica;
	}
	p{
		color:red;
		font-size: 14pt;
		text-align: center;
		font-family: Times;
	}
	button["Facebook"]{
		background: blue;
		color:white;
		text-align: center;
	}
	/*ul {
      padding: 10pt;
      background: rgba(255,0,0,0.5);
      color:#fff;
      text-align:right;*/
    }
    li {
      display: inline;
      padding: 0pt 10pt 0pt 10pt;
      color:#fff;
      text-align:right;
    }
    form{text-align: center;}
    a{text-align: center;}
	.share{ text-align: center;
		margin: 30pt 0pt 0pt 0pt;
  border:4pt solid white;
  border-radius: 50%;
  display: inline-table;
}
		*:focus {
    		outline: none;
		}
		header {
			background: url("http://i.imgur.com/PVYiioJ.jpg");
			height: 99pt;
		}
		.footer p {
			color: black;
			position: absolute;
			bottom: 0;
		}
		body{
			background-color: rgb(225,225,225);
		}
		h1 {
		    font-family: playfair display;
		    font-size: 16pt;
		    font-weight: bold;
		}
		p { 
			font-family: raleway;
			color: rgb(56,56,56);
			font-size: 10pt;
		}
		a {
			color: black;
			text-align: center;
			font-family: alegreya;
			font-weight: none;
			text-decoration: none;
			display: block;
			width: 90pt;
			font-size: 13.5pt;
		}
		
		a:hover {
  			color: #E30613;
  			background-color: none;
  		}
		ul {
			list-style-type: none;
			margin: 0;
			padding: 0;
			position: fixed;
			top: 50pt;
			right: 0.5pt;
			position: absolute;
		}
		li {
			float: right;
		}
	</style>

</head>
<body>

<header>
	<img src="http://i.imgur.com/iDlyl4r.png" width="270" height: auto;>
	 <ul>
	    <% if user_signed_in? %>
	 	<li><%= link_to "Log Out", destroy_user_session_path, :method => :delete %></li>
	 	<% else %>
  		<li><a href="http://google.com">Login</a></li>
  		<% end %>
  		<li><a href="customs/Contact Us.html">Contact Us</a></li>
  		<li><a href="/blogposts/index.html.erb">Our Blog</a></li>
  		<li><a href="/profiles/team.html.erb">Our Team</a></li>
  		<li><a href="/Home.html">Home</a></li>
	</ul> 
	</header>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

 

<%= yield %>


<div class="footer">
<p>&copy;2015 RiddleBeans</p>
</div> 
</body>
</html>

blog/app/views/profiles/team.html.erb
<!DOCTYPE html>
<head>
	<title>RiddleBeans: Our Team</title>
	<style>

		*:focus {
    		outline: none;
		}


		.footer p {
			color: black;
			position: absolute;
			bottom: 0;
		}


		body {
			background-color: rgb(225,225,225);
		}

		h1 {
		    font-family: playfair display;
		    font-size: 16pt;
		    font-weight: bold;
		}

		p { 
			font-family: raleway;
			color: rgb(56,56,56);
			font-size: 10pt;
		}

		a {
			color: black;
			text-align: center;
			font-family: alegreya;
			font-weight: none;
			text-decoration: none;
			display: block;
			width: 90pt;
			font-size: 13.5pt;
		}

		a:hover {
  			color: #E30613;
  			background-color: none;
		}

		#one img {
			border-radius: 50%;
			background-position: left;
			background-repeat: no-repeat;
			opacity: 0.6;

		}

		#one img:hover{
			opacity: 1.0;
		}

		#two img {
			border-radius: 50%;
			background-position: center;
			background-repeat: no-repeat;
			opacity: 0.6;
		}

		#two img:hover{
			opacity: 1.0;
		}

		#three img {
			border-radius: 50%;
			background-position: center;
			background-repeat: no-repeat;
			opacity: 0.6;
		}

		#three img:hover{
			opacity: 1.0;
		}

		#four img {
			border-radius: 50%;
			background-position: center;
			background-repeat: no-repeat;
			opacity: 0.6;
		}

		#four img:hover{
			opacity: 1.0;
		}



		ul {
			list-style-type: none;
			margin: 0;
			padding: 0;
			position: fixed;
			top: 50pt;
			right: 0.5pt;
			position: absolute;
		}

		li {
			float: right;
		}
	</style>
</head>
<body>
	
	
	<div id="lside" style="float:left;margin:0; width: 8%">
	<br><br>
	</div>

	<div id="one" style="float:left;margin:0; width: 23%">
		<a href="Haya.html"><img src="http://i.imgur.com/80mojPK.jpg" width="185" height: auto;></a>
	<br><br>
		<a href="Marina.html"><img src="http://i.imgur.com/Ppd0XUB.jpg" width="185" height: auto;>
	</div>

	<div id="two" style="float:left;margin:0;width:23%">
		<a href="Christianne.html"><img src="http://i.imgur.com/Y3p1i5G.png" width="185" height: auto;></a>
	<br><br>
		<a href="Amr.html"><img src="http://i.imgur.com/zWJ7efo.jpg" width="185" height: auto;>
	</div>

	<div id="three" style="float:left;margin:0;width:23%">
		<a href="Seif.html"><img src="http://i.imgur.com/0IZ2Udth.jpg" width="185" height: auto;></a>
	<br><br>
		<a href="Sandra.html"><img src="http://i.imgur.com/u5LzxQn.jpg" width="185" height: auto;>
	</div>

	<div id="four" style="float:left;margin:0;width:23%">
		<a href="Sara.html"><img src="http://i.imgur.com/SCV2Kth.jpg" width="185" height: auto;></a>
	<br><br>
		<a href="Omar.html"><img src="http://i.imgur.com/2dzX5yl.jpg" width="185" height: auto;>
	</div>

	<div class="footer">
 	<p>&copy;2015 RiddleBeans</p>
 	</div>
 	
</body>

blog/app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<p> This is the blog's homepage </p>
    <%= link_to "sign out", destroy_user_session_path, :method => :delete %>
<h1>Hello, Rails!</h1>
<%= link_to 'Our Blog', controller: 'blogposts' %>